import { Inter } from "next/font/google";
import "./globals.css";
import { RecipesProvider } from "./Context/recipeContextProvider";
import { IngredientsProvider } from "./Context/ingredientsContext";
import { UsernameProvider } from "./Context/userContext"
import { LoggedInProvider } from "./Context/loggedInContext";

import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Grocery App',
  description: 'Generated by DSD Cohort',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Navbar />
        <LoggedInProvider>
        <UsernameProvider>
        <IngredientsProvider>
        <RecipesProvider>
          {children}
          </RecipesProvider>
        </IngredientsProvider>
        </UsernameProvider>
        </LoggedInProvider>
        <Footer />
      </body>
    </html>
  )
}
