import { Inter } from "next/font/google";
import "./globals.css";
import { RecipesProvider } from "./Context/recipeContextProvider";
import { IngredientsProvider } from "./Context/ingredientsContext";
import { UsernameProvider } from "./Context/userContext"
import { LoggedInProvider } from "./Context/loggedInContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <LoggedInProvider>
        <UsernameProvider>
        <IngredientsProvider>
        <RecipesProvider>
          {children}
          </RecipesProvider>
        </IngredientsProvider>
        </UsernameProvider>
        </LoggedInProvider>
          </body>
    </html>
  )
}
